#!/usr/bin/env bash
# Put the four applications on the local network the way ADR-0026 wants it: each app stays bound
# to loopback, one Caddy terminates TLS (its own local CA) and asks for a password, and every
# app's Host allowlist names this machine. See LAN_ACCESS.md for the client-side certificate
# trust steps this prints at the end.
#
#   docs/scripts/expose_on_lan.sh                 # interactive: asks for the LAN username/password
#   LAN_USER=jordan LAN_PASSWORD=… docs/scripts/expose_on_lan.sh
#   docs/scripts/expose_on_lan.sh --off           # stop the four app services and Caddy
#
# Idempotent: re-running rewrites the Caddyfile and units, leaves an existing [server] block in a
# config.toml alone (it says so), and restarts what changed. Needs sudo for apt and /etc/caddy.
set -euo pipefail

SUITE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOST_NAME="${LAN_HOSTNAME:-$(hostname | tr 'A-Z' 'a-z').local}"
LAN_IP="${LAN_IP:-$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)}"
CERT_PORT="${LAN_CERT_PORT:-9780}"
CADDYFILE=/etc/caddy/Caddyfile
CA_ROOT=/var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt
PUBLIC_DIR=/etc/caddy/public   # only root.crt is copied here; the CA directory itself holds private keys
UNIT_DIR="$HOME/.config/systemd/user"
# app  venv-dir      app-port  lan-port  needs-trusted-proxies
APPS=(
    "freeweight    FreeWeight    8765 9765 no"
    "loadcoach     LoadCoach     8766 9766 yes"
    "ideapress     IdeaPress     8767 9767 no"
    "promptcadence PromptCadence 8768 9768 yes"
)

say()  { printf '\n\033[1m== %s\033[0m\n' "$*"; }
fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

if [[ "${1:-}" == "--off" ]]; then
    say "stopping"
    for row in "${APPS[@]}"; do set -- $row; systemctl --user disable --now "$1.service" 2>/dev/null || true; done
    sudo systemctl disable --now caddy 2>/dev/null || true
    echo "Apps and Caddy stopped. Config files and the Caddyfile are left in place."
    exit 0
fi

[[ -n "$LAN_IP" ]] || fail "could not find the LAN address; set LAN_IP"
for row in "${APPS[@]}"; do set -- $row; [[ -x "$SUITE/$2/.venv/bin/$1" ]] || fail "$SUITE/$2/.venv/bin/$1 missing — install the app first"; done
command -v systemctl >/dev/null || fail "systemd required"
loginctl show-user "$USER" -p Linger | grep -q yes || sudo loginctl enable-linger "$USER"

say "Caddy"
if ! command -v caddy >/dev/null; then sudo apt-get install -y caddy; fi
caddy version

say "LAN login (Caddy basic auth, over TLS)"
LAN_USER="${LAN_USER:-}"; LAN_PASSWORD="${LAN_PASSWORD:-}"
[[ -n "$LAN_USER" ]] || read -r -p "username: " LAN_USER
[[ -n "$LAN_PASSWORD" ]] || { read -r -s -p "password: " LAN_PASSWORD; echo; }
[[ ${#LAN_PASSWORD} -ge 12 ]] || fail "password must be at least 12 characters"
HASH="$(printf '%s' "$LAN_PASSWORD" | caddy hash-password)"

say "app config: Host allowlist ($HOST_NAME, $LAN_IP)"
for row in "${APPS[@]}"; do
    set -- $row; app=$1; proxies=$5
    cfg="$HOME/.config/$app/config.toml"; mkdir -p "$(dirname "$cfg")"; touch "$cfg"
    if grep -qE '^\s*\[server\]' "$cfg"; then
        echo "$app: [server] already present in $cfg — left alone; make sure allowed_hosts names $HOST_NAME"
        continue
    fi
    {
        printf '\n[server]\n# LAN_ACCESS.md: the app stays on loopback; Caddy fronts it at https://%s:%s\n' "$HOST_NAME" "$4"
        printf 'allowed_hosts = ["localhost", "127.0.0.1", "%s", "%s"]\n' "$HOST_NAME" "$LAN_IP"
        [[ "$proxies" == yes ]] && printf 'trusted_proxies = ["127.0.0.0/8"]\n'
    } >> "$cfg"
    echo "$app: [server] appended to $cfg"
done

say "Caddyfile -> $CADDYFILE"
[[ -f "$CADDYFILE" ]] && sudo cp -n "$CADDYFILE" "$CADDYFILE.bak.$(date +%Y%m%d)" || true
{
    echo "# Generated by expose_on_lan.sh — the suite's four apps behind TLS + basic auth."
    echo "# Root CA for clients: http://$HOST_NAME:$CERT_PORT/root.crt  (LAN_ACCESS.md)"
    echo
    echo "(suite_auth) {"
    echo "    basicauth {"
    echo "        $LAN_USER $HASH"
    echo "    }"
    echo "}"
    echo
    for row in "${APPS[@]}"; do
        set -- $row
        echo "https://$HOST_NAME:$4, https://$LAN_IP:$4 {"
        echo "    tls internal"
        echo "    import suite_auth"
        echo "    reverse_proxy 127.0.0.1:$3"
        echo "}"
        echo
    done
    echo "http://$HOST_NAME:$CERT_PORT, http://$LAN_IP:$CERT_PORT {"
    echo "    root * $PUBLIC_DIR"
    echo "    file_server"
    echo "}"
} | sudo tee "$CADDYFILE" >/dev/null
sudo caddy validate --config "$CADDYFILE" --adapter caddyfile >/dev/null
sudo systemctl enable --now caddy
sudo systemctl reload caddy || sudo systemctl restart caddy
for _ in $(seq 1 30); do sudo test -f "$CA_ROOT" && break; sleep 1; done
sudo test -f "$CA_ROOT" || fail "Caddy did not create its local CA at $CA_ROOT (see: sudo journalctl -u caddy)"
sudo install -D -m 644 "$CA_ROOT" "$PUBLIC_DIR/root.crt"
sudo cp "$CA_ROOT" "$HOME/${HOST_NAME}-root.crt"; sudo chown "$USER" "$HOME/${HOST_NAME}-root.crt"

say "systemd --user units"
mkdir -p "$UNIT_DIR"
for row in "${APPS[@]}"; do
    set -- $row; app=$1; dir=$2
    cat > "$UNIT_DIR/$app.service" <<EOF
[Unit]
Description=$app (suite app, loopback; Caddy fronts it on the LAN)
After=network.target

[Service]
ExecStart=$SUITE/$dir/.venv/bin/$app serve
WorkingDirectory=$SUITE/$dir
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF
done
systemctl --user daemon-reload
for row in "${APPS[@]}"; do
    set -- $row
    systemctl --user enable --now "$1.service" >/dev/null
    systemctl --user restart "$1.service"
    for _ in $(seq 1 40); do curl -fs "http://127.0.0.1:$3/api/v1/health" >/dev/null && break; sleep 0.5; done
    curl -fs "http://127.0.0.1:$3/api/v1/health" >/dev/null && echo "$1: healthy on 127.0.0.1:$3" \
        || echo "$1: NOT healthy — journalctl --user -u $1 -n 50"
done

say "check through Caddy"
for row in "${APPS[@]}"; do
    set -- $row
    code="$(curl -sk -o /dev/null -w '%{http_code}' -u "$LAN_USER:$LAN_PASSWORD" "https://$HOST_NAME:$4/api/v1/health" || true)"
    echo "https://$HOST_NAME:$4  ->  HTTP $code$([[ "$code" == 200 ]] || echo '  (expected 200)')"
done
unauth="$(curl -sk -o /dev/null -w '%{http_code}' "https://$HOST_NAME:9765/" || true)"
[[ "$unauth" == 401 ]] && echo "no password -> 401 (good)" || echo "no password -> $unauth (expected 401)"

say "done"
cat <<EOF
Apps:  https://$HOST_NAME:9765 FreeWeight   https://$HOST_NAME:9766 LoadCoach
       https://$HOST_NAME:9767 IdeaPress    https://$HOST_NAME:9768 PromptCadence
       (or by address: https://$LAN_IP:<port>)   login: $LAN_USER

Every client must trust this machine's Caddy root certificate once, or the browser will
refuse the page (and the __Host- CSRF cookie will not be set, so forms would fail even if you
click through). Get it from  http://$HOST_NAME:$CERT_PORT/root.crt  — a copy is at
$HOME/${HOST_NAME}-root.crt. Per-OS steps: docs/LAN_ACCESS.md §3.

This machine: sudo cp $HOME/${HOST_NAME}-root.crt /usr/local/share/ca-certificates/ && sudo update-ca-certificates
EOF
